### ISSUE TITLE
Crash while fighting birds in act 2

### ISSUE THREAD

**Issue by idealisms** [Jerry-Licious/dome-mod#2]
Here's the stack trace. Let me know if you need any other info. Other mods:
BaseMod
Relic Stats
Slay the Relics Exporter
Minty Spire
Highlight Path
InfoMod

Exception in thread "FileSaver" java.lang.Error: Interrupted attempt to acquire write lock
	at javax.swing.text.AbstractDocument.writeLock(AbstractDocument.java:1349)
	at javax.swing.text.AbstractDocument.insertString(AbstractDocument.java:701)
	at javax.swing.text.PlainDocument.insertString(PlainDocument.java:130)
	at com.evacipated.cardcrawl.modthespire.ui.MessageConsole$ConsoleOutputStream.clearBuffer(MessageConsole.java:226)
	at com.evacipated.cardcrawl.modthespire.ui.MessageConsole$ConsoleOutputStream.handleAppend(MessageConsole.java:183)23:50:09.921 INFO core.CardCrawlGame> Flushing logs to disk. Clean shutdown successful.

	at com.evacipated.cardcrawl.modthespire.ui.MessageConsole$ConsoleOutputStream.flush(MessageConsole.java:154)
	at java.io.PrintStream.write(PrintStream.java:482)
	at org.apache.logging.log4j.core.util.CloseShieldOutputStream.write(CloseShieldOutputStream.java:53)
	at org.apache.logging.log4j.core.appender.OutputStreamManager.writeToDestination(OutputStreamManager.java:262)
	at org.apache.logging.log4j.core.appender.OutputStreamManager.flushBuffer(OutputStreamManager.java:294)
	at org.apache.logging.log4j.core.appender.OutputStreamManager.flush(OutputStreamManager.java:303)
	at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.directEncodeEvent(AbstractOutputStreamAppender.java:179)
	at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.tryAppend(AbstractOutputStreamAppender.java:170)
	at org.apache.logging.log4j.core.appender.AbstractOutputStreamAppender.append(AbstractOutputStreamAppender.java:161)
	at org.apache.logging.log4j.core.config.AppenderControl.tryCallAppender(AppenderControl.java:156)
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender0(AppenderControl.java:129)
	at org.apache.logging.log4j.core.config.AppenderControl.callAppenderPreventRecursion(AppenderControl.java:120)
	at org.apache.logging.log4j.core.config.AppenderControl.callAppender(AppenderControl.java:84)
	at org.apache.logging.log4j.core.config.LoggerConfig.callAppenders(LoggerConfig.java:448)
	at org.apache.logging.log4j.core.config.LoggerConfig.processLogEvent(LoggerConfig.java:433)
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:417)
	at org.apache.logging.log4j.core.config.LoggerConfig.log(LoggerConfig.java:403)
	at org.apache.logging.log4j.core.config.AwaitCompletionReliabilityStrategy.log(AwaitCompletionReliabilityStrategy.java:63)
	at org.apache.logging.log4j.core.Logger.logMessage(Logger.java:146)
	at org.apache.logging.log4j.spi.AbstractLogger.tryLogMessage(AbstractLogger.java:2116)
	at org.apache.logging.log4j.spi.AbstractLogger.logMessageSafely(AbstractLogger.java:2100)
	at org.apache.logging.log4j.spi.AbstractLogger.logMessage(AbstractLogger.java:1994)
	at org.apache.logging.log4j.spi.AbstractLogger.logIfEnabled(AbstractLogger.java:1966)
	at org.apache.logging.log4j.spi.AbstractLogger.info(AbstractLogger.java:1303)
	at com.megacrit.cardcrawl.helpers.FileSaver.run(FileSaver.java:31)
	at java.lang.Thread.run(Thread.java:748)Game crashed.
Cause:
java.lang.NullPointerException
	at domemod.moves.MoveInfo.flashIntent(MoveInfo.kt:287)
	at domemod.moves.AscensionMoveSet.flashIntent(AscensionMoveSet.kt:43)
	at domemod.patches.MonsterFlashIntentPatch$Companion.flashIntents(MonsterFlashIntentPatch.kt:18)
	at domemod.patches.MonsterFlashIntentPatch.flashIntents(MonsterFlashIntentPatch.kt)
	at com.megacrit.cardcrawl.monsters.AbstractMonster.flashIntent(AbstractMonster.java)
	at com.megacrit.cardcrawl.actions.IntentFlashAction.update(IntentFlashAction.java:24)
	at com.megacrit.cardcrawl.actions.GameActionManager.update(GameActionManager.java:179)
	at com.megacrit.cardcrawl.rooms.AbstractRoom.update(AbstractRoom.java:325)
	at com.megacrit.cardcrawl.dungeons.AbstractDungeon.update(AbstractDungeon.java:2532)
	at com.megacrit.cardcrawl.core.CardCrawlGame.update(CardCrawlGame.java:871)
	at com.megacrit.cardcrawl.core.CardCrawlGame.render(CardCrawlGame.java:419)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication.mainLoop(LwjglApplication.java:225)
	at com.badlogic.gdx.backends.lwjgl.LwjglApplication$1.run(LwjglApplication.java:126)

**Comment by Jerry-licious** [comment]
When the monsters take their turn, they "flash" their intent icon. In the case of Byrds, they have a "stun" move, and in the game there are no icons associated with the stun move. Since I required the image to be non-null, the game crashed because there is no image to be flashed. I will remove the non-null requirement in the next update.
